module.exports =
  google:
    "Afrikaans" : "af"
    "Albanian" : "sq"
    "Arabic" : "ar"
    "Armenian" : "hy"
    "Bengali" : "bn"
    "Catalan" : "ca"
    "Chinese" : "zh"
    "Chinese (Mandarin/China)" : "zh-cn"
    "Chinese (Mandarin/Taiwan)" : "zh-tw"
    "Chinese (Cantonese)" : "zh-yue"
    "Croatian" : "hr"
    "Czech" : "cs"
    "Danish" : "da"
    "Dutch" : "nl"
    "English" : "en"
    "English (Australia)" : "en-au"
    "English (Great Britain)" : "en-gb"
    "English (United States)" : "en-us"
    "Esperanto" : "eo"
    "Finnish" : "fi"
    "Franch" : "fr"
    "German" : "de"
    "Greek" : "el"
    "Hindi" : "hi"
    "Hungarian" : "hu"
    "Icelandic" : "is"
    "Indonesian" : "id"
    "Italian" : "it"
    "Japanese" : "ja"
    "Korean" : "ko"
    "Latin" : "la"
    "Latvian" : "lv"
    "Macedonian" : "mk"
    "Norwegian" : "no"
    "Polish" : "pl"
    "Portuguese" : "pt"
    "Portuguese (Brazil)" : "pt-br"
    "Romanian" : "ro"
    "Russian" : "ru"
    "Serbian" : "sr"
    "Slovak" : "sk"
    "Spanish" : "es"
    "Spanish (Spain)" : "es-es"
    "Spanish (United States)" : "es-us"
    "Swahili" : "sw"
    "Swedish" : "sv"
    "Tamil" : "ta"
    "Thai" : "th"
    "Turkish" : "tr"
    "Vietnamese" : "vi"
    "Welsh" : "cy"
  voiceRss:
    "Catalan": "ca-es"
    "Chinese (China)": "zh-cn"
    "Chinese (Hong Kong)": "zh-hk"
    "Chinese (Taiwan)": "zh-tw"
    "Danish": "da-dk"
    "Dutch": "nl-nl"
    "English (Australia)": "en-au"
    "English (Canada)": "en-ca"
    "English (Great Britain)": "en-gb"
    "English (India)": "en-in"
    "English (United States)": "en-us"
    "Finnish": "fi-fi"
    "French (Canada)": "fr-ca"
    "French (France)": "fr-fr"
    "German": "de-de"
    "Italian": "it-it"
    "Japanese": "ja-jp"
    "Korean": "ko-kr"
    "Norwegian": "nb-no"
    "Polish": "pl-pl"
    "Portuguese (Brazil)": "pt-br"
    "Portuguese (Portugal)": "pt-pt"
    "Russian": "ru-ru"
    "Spanish (Mexico)": "es-mx"
    "Spanish (Spain)": "es-es"
    "Swedish (Sweden)": "sv-se"


